-- SIMPLE SELECT CURSOR
DECLARE
EMP_NAME EMP.ENAME%TYPE;
EMP_JOB EMP.JOB%TYPE;

CURSOR EMP_LIST_CURSOR IS SELECT ENAME,JOB FROM EMP;
BEGIN
    OPEN EMP_LIST_CURSOR;
    FETCH EMP_LIST_CURSOR INTO EMP_NAME, EMP_JOB;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||EMP_NAME||'JOB: '||EMP_JOB);

    FETCH EMP_LIST_CURSOR INTO EMP_NAME, EMP_JOB;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||EMP_NAME||'JOB: '||EMP_JOB);
    CLOSE EMP_LIST_CURSOR;
END;

-- CURSOR WITH LOOP
DECLARE
EMP_NAME EMP.ENAME%TYPE;
EMP_JOB EMP.JOB%TYPE;

CURSOR EMP_LIST_CURSOR IS SELECT ENAME,JOB FROM EMP;
BEGIN
    OPEN EMP_LIST_CURSOR;
    LOOP
        FETCH EMP_LIST_CURSOR INTO EMP_NAME, EMP_JOB;
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||EMP_NAME||'JOB: '||EMP_JOB);
        EXIT WHEN EMP_LIST_CURSOR%NOTFOUND;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('NUMBER OF ROWS FETCHED : '||EMP_LIST_CURSOR%ROWCOUNT);
    CLOSE EMP_LIST_CURSOR;
END;

-- FETCH EMPLOYEE NAME, DEPARTMENT NAME FROM EMP AND DEPT TABLES USING CURSOR

SELECT * FROM EMP;

SELECT * FROM DEPT;

SELECT ENAME, DNAME FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

DECLARE
ENAME EMP.ENAME%TYPE;
DNAME DEPT.DNAME%TYPE;
CURSOR DEPT_EMP_CURSOR IS SELECT ENAME, DNAME FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;
BEGIN
    OPEN DEPT_EMP_CURSOR;
    LOOP
        FETCH DEPT_EMP_CURSOR INTO ENAME, DNAME;
        DBMS_OUTPUT.PUT_LINE(ENAME||':'||DNAME);
        EXIT WHEN DEPT_EMP_CURSOR%NOTFOUND;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Rows Fetched '||DEPT_EMP_CURSOR%ROWCOUNT);
    CLOSE DEPT_EMP_CURSOR;
END;
    
-- CURSOR WITH ARGUMENTS
DECLARE
EMP_NAME EMP.ENAME%TYPE;
EMP_SAL EMP.SAL%TYPE;
EMP_JOB EMP.JOB%TYPE;

CURSOR EMP_DNAME_CURSOR(DEPT_NO NUMBER) IS SELECT ENAME, SAL, JOB FROM EMP WHERE DEPTNO = DEPT_NO; -- WITH CURSOR ARGUMENTS WE NEED TO SPECIFY THE TYPE OF ARGUMENT
BEGIN
    OPEN EMP_DNAME_CURSOR(10);
    LOOP
        FETCH EMP_DNAME_CURSOR INTO EMP_NAME, EMP_SAL, EMP_JOB;
        DBMS_OUTPUT.PUT_LINE('NAME: '||EMP_NAME||' SAL: '||EMP_SAL||' JOB:'||EMP_JOB);
        EXIT WHEN EMP_DNAME_CURSOR%NOTFOUND;
    END LOOP;
        DBMS_OUTPUT.PUT_LINE('ROWS FETCHED '||EMP_DNAME_CURSOR%ROWCOUNT);
    CLOSE EMP_DNAME_CURSOR;
END;

-- FETCHING DATA FROM CURSOR WITHOUT USING EXTERNAL VARIABLES BY JUST USING FOR-LOOP
DECLARE
CURSOR EMP_DATA_CURSOR IS SELECT ENAME, SAL, JOB FROM EMP;
BEGIN
    FOR I IN EMP_DATA_CURSOR
    LOOP
        DBMS_OUTPUT.PUT_LINE('NAME :'||I.ENAME||' ->'||'SAL:'||I.SAL||' ->JOB:'||I.JOB);
    END LOOP;
END;

-- REFERENCE CURSOR IS USED TO GET A REFERENCE OF A QUERY. WE CAN USE MULTIPLE QUERIES ON A SINGLE REFERENCE CURSOR
DECLARE
TYPE EMP_REF_CURSOR IS REF CURSOR;
EMP_LIST EMP_REF_CURSOR;

NAME VARCHAR2(30);
EMP_SAL NUMBER;
DEPTNAME VARCHAR2(30);
DEPT_LOCATION VARCHAR2(30);
BEGIN
    OPEN EMP_LIST FOR SELECT ENAME, SAL FROM EMP;
    DBMS_OUTPUT.PUT_LINE('------EMPLOYEE LIST------------');
    LOOP
        FETCH EMP_LIST INTO NAME,EMP_SAL;
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||NAME||' | '||'EMPLOYEE SALARY : '||EMP_SAL);
        EXIT WHEN EMP_LIST%NOTFOUND;
    END LOOP;
    CLOSE EMP_LIST;

    OPEN EMP_LIST FOR SELECT DNAME, LOC FROM DEPT;
    LOOP
        FETCH EMP_LIST INTO DEPTNAME, DEPT_LOCATION;
        DBMS_OUTPUT.PUT_LINE('DEPT:'||DEPTNAME||'    '||'LOCATION:'||DEPT_LOCATION);
        EXIT WHEN EMP_LIST%NOTFOUND;
    END LOOP;
    CLOSE EMP_LIST;
END;


-- CURSOR WITH RETURN 
DECLARE
TYPE REFERENCE_CUR_DEPT IS REF CURSOR RETURN DEPT%ROWTYPE;
DEPT_LIST REFERENCE_CUR_DEPT;
DEPT_ROW DEPT%ROWTYPE;
BEGIN
    OPEN DEPT_LIST FOR SELECT * FROM DEPT;
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME LIST');
    DBMS_OUTPUT.PUT_LINE('-----------------------');
    LOOP
        FETCH DEPT_LIST INTO DEPT_ROW;
        DBMS_OUTPUT.PUT_LINE('DEPT NO '||DEPT_ROW.DEPTNO);
        DBMS_OUTPUT.PUT_LINE('DEPT NAME '||DEPT_ROW.DNAME);
        DBMS_OUTPUT.PUT_LINE('LOCATION '||DEPT_ROW.LOC);
        EXIT WHEN DEPT_LIST%NOTFOUND;
    END LOOP;
    CLOSE DEPT_LIST;
END;





