-- SIMPLE SELECT CURSOR
DECLARE
EMP_NAME EMP.ENAME%TYPE;
EMP_JOB EMP.JOB%TYPE;

CURSOR EMP_LIST_CURSOR IS SELECT ENAME,JOB FROM EMP;
BEGIN
    OPEN EMP_LIST_CURSOR;
    FETCH EMP_LIST_CURSOR INTO EMP_NAME, EMP_JOB;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||EMP_NAME||'JOB: '||EMP_JOB);

    FETCH EMP_LIST_CURSOR INTO EMP_NAME, EMP_JOB;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||EMP_NAME||'JOB: '||EMP_JOB);
    CLOSE EMP_LIST_CURSOR;
END;

-- CURSOR WITH LOOP
DECLARE
EMP_NAME EMP.ENAME%TYPE;
EMP_JOB EMP.JOB%TYPE;

CURSOR EMP_LIST_CURSOR IS SELECT ENAME,JOB FROM EMP;
BEGIN
    OPEN EMP_LIST_CURSOR;
    LOOP
        FETCH EMP_LIST_CURSOR INTO EMP_NAME, EMP_JOB;
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : '||EMP_NAME||'JOB: '||EMP_JOB);
        EXIT WHEN EMP_LIST_CURSOR%NOTFOUND;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('NUMBER OF ROWS FETCHED : '||EMP_LIST_CURSOR%ROWCOUNT);
    CLOSE EMP_LIST_CURSOR;
END;

-- FETCH EMPLOYEE NAME, DEPARTMENT NAME FROM EMP AND DEPT TABLES USING CURSOR

SELECT * FROM EMP;

SELECT * FROM DEPT;

SELECT ENAME, DNAME FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

DECLARE
ENAME EMP.ENAME%TYPE;
DNAME DEPT.DNAME%TYPE;
CURSOR DEPT_EMP_CURSOR IS SELECT ENAME, DNAME FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;
BEGIN
    OPEN DEPT_EMP_CURSOR;
    LOOP
        FETCH DEPT_EMP_CURSOR INTO ENAME, DNAME;
        DBMS_OUTPUT.PUT_LINE(ENAME||':'||DNAME);
        EXIT WHEN DEPT_EMP_CURSOR%NOTFOUND;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Rows Fetched '||DEPT_EMP_CURSOR%ROWCOUNT);
    CLOSE DEPT_EMP_CURSOR;
END;
    