INSERT ALL
    INTO RESULT VALUES ('EXM006', '40001', 'SUB001', 95)
    INTO RESULT VALUES ('EXM007', '40002', 'SUB002', 78)
    INTO RESULT VALUES ('EXM008', '40003', 'SUB003', 85)
    INTO RESULT VALUES ('EXM009', '40004', 'SUB004', 90)
    INTO RESULT VALUES ('EXM010', '40005', 'SUB005', 82)
SELECT * FROM dual;

SELECT * FROM RESULT;

SELECT * FROM EXAM_TBL;

INSERT ALL
    INTO exam_tbl VALUES ('EXM006', 'MID_TERM', 'CLS001', TO_DATE('09-15-2021', 'MM-DD-YYYY'))
    INTO exam_tbl VALUES ('EXM007', 'FINAL', 'CLS002', TO_DATE('06-05-2021', 'MM-DD-YYYY'))
    INTO exam_tbl VALUES ('EXM008', 'HALF_YEARLY', 'CLS003', TO_DATE('11-10-2021', 'MM-DD-YYYY'))
    INTO exam_tbl VALUES ('EXM009', 'MID_TERM', 'CLS004', TO_DATE('10-20-2021', 'MM-DD-YYYY'))
    INTO exam_tbl VALUES ('EXM010', 'FINAL', 'CLS005', TO_DATE('12-15-2021', 'MM-DD-YYYY'))
SELECT * FROM dual;

SELECT * FROM EXAM_TBL;

SELECT * FROM TEACHER_TBL;

select * FROM SUBJECT_TBL;

SELECT * FROM CLASS_TBL;

SELECT * FROM STUDENT_DTL;

INSERT INTO SUBJECT_TBL VALUES('SUB006','SPORTS');
INSERT INTO SUBJECT_TBL VALUES('SUB007','HISTORY');

SELECT STUDENT_DTL.NAME, CLASS_TBL.CLASS_NAME, TEACHER_TBL.TEACHER_NAME FROM STUDENT_DTL JOIN CLASS_TBL ON STUDENT_DTL.CLASS_ID = CLASS_TBL.CLASS_ID JOIN TEACHER_TBL ON CLASS_TBL.TEACHER_ID = TEACHER_TBL.TEACHER_ID;

SELECT ADMN_NO, NAME, CLASS_ID, TOTAL_MARKS FROM (SELECT ADMN_NO, NAME, CLASS_ID, TOTAL_MARKS FROM STUDENT_DTL ORDER BY TOTAL_MARKS DESC) WHERE ROWNUM<=3;

SELECT * FROM SUBJECT_TBL WHERE SUBJ_ID NOT IN (SELECT SUBJECT_ID FROM TEACHER_TBL);

SELECT STUDENT_DTL.NAME, SUBJECT_TBL.SUBJECT_NAME, RESULT.MARKS FROM STUDENT_DTL JOIN RESULT ON STUDENT_DTL.ADMN_NO = RESULT.ADMN_NO JOIN SUBJECT_TBL ON SUBJECT_TBL.SUBJ_ID=RESULT.SUBJ_ID;

DESC RESULT;

INSERT INTO teacher_tbl VALUES('T005','Raymond Mosley','02-10-1978','SUB001','987654321','10-05-2012');	

INSERT ALL
    INTO RESULT VALUES ('EXM001', '40001', 'SUB001', 95)
    INTO RESULT VALUES ('EXM001', '40002', 'SUB002', 78)
    INTO RESULT VALUES ('EXM001', '40003', 'SUB003', 85)
    INTO RESULT VALUES ('EXM001', '40004', 'SUB004', 90)
    INTO RESULT VALUES ('EXM001', '40005', 'SUB005', 82)
SELECT * FROM dual;

SELECT DISTINCT EXAM_ID, R.ADMN_NO, NAME, SUBJECT_NAME, MARKS FROM RESULT R JOIN STUDENT_DTL S ON R.ADMN_NO = S.ADMN_NO JOIN SUBJECT_TBL ST ON
ST.SUBJ_ID = R.SUBJ_ID WHERE(R.ADMN_NO, R.MARKS) IN (SELECT ADMN_NO, MAX(MARKS) FROM RESULT GROUP BY ADMN_NO);

SELECT AVG(AVGMARKS) AS AVERAGE, SUBJECT FROM (SELECT DISTINCT S.SUBJ_ID, S.SUBJECT_NAME AS SUBJECT, R.MARKS AS AVGMARKS FROM 
SUBJECT_TBL S JOIN RESULT R ON R.SUBJ_ID=S.SUBJ_ID) GROUP BY SUBJECT;





