CREATE OR REPLACE PROCEDURE ADD_DEPT(
    IN_DEPT_NO IN NUMBER,
    IN_DEPT_NAME IN VARCHAR2,
    IN_LOC IN VARCHAR2
) AS BEGIN
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(IN_DEPT_NO, IN_DEPT_NAME, IN_LOC);
DBMS_OUTPUT.PUT_LINE('DEPT ADDED '||IN_DEPT_NO||' SUCCESSFULLY!');
END;

BEGIN
    ADD_DEPT(92, 'RAHUK', 'IRINJALAKKUDA');
END;

SELECT * FROM DEPT;

DESC DEPT;

CREATE OR REPLACE PROCEDURE DELETE_DEPT(
    DEPT_ID DEPT.DEPTNO%TYPE
) AS BEGIN
    DELETE FROM DEPT WHERE DEPTNO = DEPT_ID;
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT DELETED'||DEPT_ID||' SUCCESSFULLY!');
END;

BEGIN 
    DELETE_DEPT(92);
END;

CREATE OR REPLACE PROCEDURE UPDATE_DEPT(
    DEPT_ID DEPT.DEPTNO%TYPE,
    DEPT_LOC DEPT.LOC%TYPE
) AS BEGIN
UPDATE DEPT SET LOC=DEPT_LOC WHERE DEPTNO=DEPT_ID;
DBMS_OUTPUT.PUT_LINE('RECORD UPDATED ' ||DEPT_ID||' SUCCESSFULLY!');
END;

BEGIN
    UPDATE_DEPT(90, 'MUMBAI');
END;

SELECT * FROM DEPT;