-- string functions
SELECT UPPER('bilu') FROM DUAL;

SELECT LOWER('SP') FROM DUAL;

SELECT INITCAP('rahul mon') FROM DUAL;

SELECT LENGTH('RAHUL') FROM DUAL;

SELECT SUBSTR('RAHUL', 2,4) FROM DUAL;

SELECT INSTR('RAHUL', 'U') FROM DUAL;

SELECT LPAD('RAHUL', 10, 'MON') FROM DUAL;

SELECT RPAD('RAHUL',8,'*') FROM DUAL;

SELECT CONCAT('RAHUL','MON') FROM DUAL;

SELECT LPAD(NAME, 15, 'MR') FROM STUDENT_DTL;

SELECT * FROM STUDENT_DTL;

SELECT TRANSLATE('COME','O','A') FROM DUAL;

SELECT REPLACE('WELCOME','WELCOME', 'HELLO') FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT CURRENT_DATE FROM DUAL;

SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT TO_DATE('23/11/2018') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DAY DD MONTH YYYY') FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, -2) FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, '11/02/1999') FROM DUAL;

SELECT LAST_DAY(SYSDATE) FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'FRIDAY') FROM DUAL;

SELECT TRUNC(SYSDATE,'yy')+1 FROM DUAL; -- SHOWS THE STARTING OF THE GIVEN MONTH, YEAR OR DAY.
-- IF NOTHING IS SPECIFIED. IF 

SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'FMWW') FROM DUAL; -- FM IS USED FOR FORMATTING

