CREATE OR REPLACE PROCEDURE proc_transaction IS PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO DEPT VALUES(70, 'QA', 'EDL');

    INSERT INTO DEPT VALUES(33, 'HR', 'LA');

    SAVEPOINT PROCESS;

    INSERT INTO DEPT VALUES(66, 'ADMIN', 'HO');

    ROLLBACK TO PROCESS;

    COMMIT;
END;

    BEGIN
        proc_transaction;
    END;

    SELECT * FROM DEPT;